import type { App } from 'vue'
import { createVfm } from 'vue-final-modal'

export { Accordion } from './components/Accordion/index.ts'
export { AttachmentList } from './components/AttachmentList/index.ts'
export { Avatar } from './components/Avatar/index.ts'
export { AvatarGroup } from './components/AvatarGroup/index.ts'
export { Badge } from './components/Badge/index.ts'
export { Button } from './components/Button/index.ts'
export { Card } from './components/Card/index.ts'
export { Checkbox } from './components/Checkbox/index.ts'
export { ClickableTag } from './components/ClickableTag/index.ts'
export { CodeSnippet } from './components/CodeSnippet/index.ts'
export { CurrencyInput } from './components/CurrencyInput/index.ts'
export { DatePicker } from './components/DatePicker/index.ts'
export { DragAndDropFiles } from './components/DragAndDropFiles/index.ts'
export { DropdownMenu } from './components/DropdownMenu/index.ts'
export { DropdownOptions } from './components/DropdownOptions/index.ts'
export { Dropzone } from './components/Dropzone/index.ts'
export { FileButton } from './components/FileButton/index.ts'
export { FileList } from './components/FileList/index.ts'
export { HoverBox } from './components/HoverBox/index.ts'
export { IconButton } from './components/IconButton/index.ts'
export { Loader } from './components/Loader/index.ts'
export { MediaCarousel } from './components/MediaCarousel/index.ts'
export { MediaInput } from './components/MediaInput/index.ts'
export { Modal } from './components/Modal/index.ts'
export { Multiselect } from './components/Multiselect/index.ts'
export { NumberInput } from './components/NumberInput/index.ts'
export { Paragraph } from './components/Paragraph/index.ts'
export { Radio } from './components/Radio/index.ts'
export { Select } from './components/Select/index.ts'
export { Stepper } from './components/Stepper/index.ts'
export { StopPropagation } from './components/StopPropagation/index.ts'
export { TableCard } from './components/TableCard/index.ts'
export { Tabs } from './components/Tabs/index.ts'
export { Tag } from './components/Tag/index.ts'
export { Textarea } from './components/Textarea/index.ts'
export { Textbox } from './components/Textbox/index.ts'
export { ToastContainer } from './components/Toast/index.ts'
export { Toggle } from './components/Toggle/index.ts'
export { Tooltip } from './components/Tooltip/index.ts'
export { useFiles } from './composables/useFiles.ts'
export { useIsHandheld } from './composables/useIsHandheld.ts'
export { useToast } from './composables/useToast.ts'

// Export existing types
export type { FormattedFile, FileInput } from './types/file'
export type { ToastMessageInput as ToastMessage } from './types/toast'

// Export component types
export type { AccordionProps, AccordionSlots, AccordionEmits } from './components/Accordion'
export type { AttachmentListProps, AttachmentListSlots, AttachmentListEmits } from './components/AttachmentList'
export type { AvatarProps, AvatarSlots, AvatarEmits } from './components/Avatar'
export type { AvatarGroupProps, AvatarGroupSlots, AvatarGroupEmits } from './components/AvatarGroup'
export type { BadgeProps, BadgeSlots, BadgeEmits } from './components/Badge'
export type { ButtonProps, ButtonSlots, ButtonEmits } from './components/Button'
export type { CardProps, CardSlots, CardEmits } from './components/Card'
export type { CheckboxProps, CheckboxSlots, CheckboxEmits } from './components/Checkbox'
export type { ClickableTagProps, ClickableTagSlots, ClickableTagEmits } from './components/ClickableTag'
export type { CodeSnippetProps, CodeSnippetSlots, CodeSnippetEmits } from './components/CodeSnippet'
export type { CurrencyInputProps, CurrencyInputSlots, CurrencyInputEmits } from './components/CurrencyInput'
export type { DatePickerProps, DatePickerSlots, DatePickerEmits } from './components/DatePicker'
export type { DragAndDropFilesProps, DragAndDropFilesSlots, DragAndDropFilesEmits } from './components/DragAndDropFiles'
export type { DropdownMenuProps, DropdownMenuSlots, DropdownMenuEmits } from './components/DropdownMenu'
export type { DropdownOptionsProps, DropdownOptionsSlots, DropdownOptionsEmits } from './components/DropdownOptions'
export type { DropzoneProps, DropzoneSlots, DropzoneEmits } from './components/Dropzone'
export type { FileButtonProps, FileButtonSlots, FileButtonEmits } from './components/FileButton'
export type { FileListProps, FileListSlots, FileListEmits } from './components/FileList'
export type { HoverBoxProps, HoverBoxSlots, HoverBoxEmits } from './components/HoverBox'
export type { IconButtonProps, IconButtonSlots, IconButtonEmits } from './components/IconButton'
export type { LoaderProps, LoaderSlots, LoaderEmits } from './components/Loader'
export type { MediaCarouselProps, MediaCarouselSlots, MediaCarouselEmits } from './components/MediaCarousel'
export type { MediaInputProps, MediaInputSlots, MediaInputEmits } from './components/MediaInput'
export type { ModalProps, ModalSlots, ModalEmits } from './components/Modal'
export type { MultiselectProps, MultiselectSlots, MultiselectEmits } from './components/Multiselect'
export type { NumberInputProps, NumberInputSlots, NumberInputEmits } from './components/NumberInput'
export type { ParagraphProps, ParagraphSlots, ParagraphEmits } from './components/Paragraph'
export type { RadioProps, RadioSlots, RadioEmits } from './components/Radio'
export type { SelectProps, SelectSlots, SelectEmits } from './components/Select'
export type { StepperProps, StepperSlots, StepperEmits, Step } from './components/Stepper'
export type { StopPropagationProps, StopPropagationSlots, StopPropagationEmits } from './components/StopPropagation'
export type { TableCardProps, TableCardSlots, TableCardEmits, Cell, Row } from './components/TableCard'
export type { TabsProps, TabsSlots, TabsEmits, Tab } from './components/Tabs'
export type { TagProps, TagSlots, TagEmits } from './components/Tag'
export type { TextareaProps, TextareaSlots, TextareaEmits } from './components/Textarea'
export type { TextboxProps, TextboxSlots, TextboxEmits } from './components/Textbox'
export type { ToastContainerProps, ToastContainerSlots, ToastContainerEmits } from './components/Toast'
export type { ToggleProps, ToggleSlots, ToggleEmits } from './components/Toggle'
export type { TooltipProps, TooltipSlots, TooltipEmits } from './components/Tooltip'

export default {
    install(app: App) {
        const vfm = createVfm()
        app.use(vfm)
    }
}